// IMPORTING REACT
import React from 'react'
// A LITTLE CSS
import './Btn.css'

// BELOW WE ARE USING THE THREE PROPS PASSED INTO BTN AT VARIOUS PLACES IN THE CODE. 1 TEXT, 2 METHOD, 3 CLASSES
// CLASSES IS JUST A STRING OF CLASSES WE WANT TO USE FOR STYLING
// METHOD IS THE METHO WE WILL USE WHEN OUR BTN COMPONENT IS CLICKED
// TEXT IS THE TEXT THAT WILL DISPLAY INSIDE OF THE TWO BUTTON TAGS
// BTN IS A FUNCTIONAL COMPONENT MEANING IT DOES NOT HAVE ACCESS TO STATE OR CUSTOM METHODS ALONG WITH LIFECYCLE METHHODS

const Btn = ({ text, method, classes }) => <button className={classes} onClick={method}>{text}</button>

export default Btn
